const FiltersTab = [
  {
    id: 1,
    image: "https://img.icons8.com/?size=1x&id=f2Pd07NxP50-&format=png",
    title: "Voyage",
    theme: "travel",
    active: false,
    classe: "image-filter",
  },
  {
    id: 2,
    image: "https://img.icons8.com/?size=1x&id=CwT76QEIQphR&format=png",
    title: "Action / Aventure",
    theme: "action-adventure",
    active: false,
    classe: "image-filter",
  },
  {
    id: 3,
    image: "https://img.icons8.com/?size=1x&id=KJo4_dTC-coU&format=png",
    title: "Comédie",
    theme: "comedy",
    active: false,
    classe: "image-filter",
  },
  {
    id: 4,
    image: "https://img.icons8.com/?size=1x&id=edESY4RJ6d_B&format=png",
    title: "Science Fiction",
    theme: "sci-fi",
    active: false,
    classe: "image-filter",
  },
  {
    id: 5,
    image: "https://img.icons8.com/?size=1x&id=95263&format=png",
    title: "Fantastique",
    theme: "fantasy",
    active: false,
    classe: "image-filter",
  },
  {
    id: 6,
    image: "https://img.icons8.com/?size=1x&id=48959&format=png",
    title: "Policier",
    theme: "detective fiction",
    active: false,
    classe: "image-filter",
  },
  {
    id: 7,
    image: "https://img.icons8.com/?size=1x&id=ExjPRAX81HOH&format=png",
    title: "Guerre",
    theme: "war",
    active: false,
    classe: "image-filter",
  },
  {
    id: 8,
    image: "https://img.icons8.com/?size=1x&id=49649&format=png",
    title: "Automobile",
    theme: "motoring",
    active: false,
    classe: "image-filter",
  },
  {
    id: 9,
    image: "https://img.icons8.com/?size=1x&id=49597&format=png",
    title: "Culinaire",
    theme: "cooking",
    active: false,
    classe: "image-filter",
  },
  {
    id: 10,
    image: "https://img.icons8.com/?size=1x&id=3OfJfNUd1BuI&format=png",
    title: "Relaxation",
    theme: "relax",
    active: false,
    classe: "image-filter",
  },
  {
    id: 11,
    image: "https://img.icons8.com/?size=1x&id=49604&format=png",
    title: "Romantique",
    theme: "romance",
    active: false,
    classe: "image-filter",
  },
  {
    id: 12,
    image: "https://img.icons8.com/?size=1x&id=1EJcqeUdGuvU&format=png",
    title: "Pornographique",
    theme: "porn",
    active: false,
    classe: "image-filter",
  },
  {
    id: 13,
    image: "https://img.icons8.com/?size=1x&id=Whkx361Z-IK1&format=png",
    title: "Protagoniste",
    active: false,
    classe: "image-filter",
  },
  {
    id: 14,
    image: "https://img.icons8.com/?size=1x&id=M61Ezw-zpoy6&format=png",
    title: "Antagoniste",
    active: false,
    classe: "image-filter",
  },
  {
    id: 15,
    image: "https://img.icons8.com/?size=1x&id=yWgzoxYD__3z&format=png",
    title: "Lieux",
    active: false,
    classe: "image-filter",
  },
  {
    id: 16,
    image: "https://img.icons8.com/?size=1x&id=58892&format=png",
    title: "Actions",
    active: false,
    classe: "image-filter",
  },
  {
    id: 17,
    image: "https://img.icons8.com/?size=1x&id=JWeOybaezIaa&format=png",
    title: "Objects",
    active: false,
    classe: "image-filter",
  },
  {
    id: 18,
    image: "https://img.icons8.com/?size=1x&id=103848&format=png",
    title: "Véhicules",
    active: false,
    classe: "image-filter",
  },
  {
    id: 19,
    image: "https://img.icons8.com/?size=1x&id=66496&format=png",
    title: "Météo",
    active: false,
    classe: "image-filter",
  },
];

export default FiltersTab;
